In [9]:
import plotly.plotly as py
import plotly.figure_factory as ff
import numpy as np
import pandas as pd

py.sign_in('ryanjhenry', 'NMuKOojLAVUAxe43Zeqf')

In [10]:
df_sample = pd.read_excel(r'C:\Users\ryguy\Documents\Muni Listing.xlsx',skiprows=1)
df_sample.head()
# I had to use skiprows because unnamed kept showing up.
# Also, fucking ONEDRIVE motherfucker not having admin access

,Cusip,Account,Name,County,State,County_State,FIPS_txt,FIPs,Sector,Population,...,Purpose,Credit Support,YTW,TEY,Par Value,Bk Price,Bk Value,Mkt Price,Mkt Value,G/L
0,733123BN2,HTM,POPLAR CREEK PUB LIBR DIST ILL,Cook,IL,"Cook, IL",17031.0,17031.0,Libraries,40615.0,...,Other,AGC,3.719,4.671,500000,100.150,500750.00,101.344,506720.00,5970.00
1,733123BP7,HTM,POPLAR CREEK PUB LIBR DIST ILL,Cook,IL,"Cook, IL",17031.0,17031.0,Libraries,40615.0,...,Other,AGC,3.815,4.793,500000,100.274,501370.00,103.876,519380.00,18010.00
2,733123BQ5,HTM,POPLAR CREEK PUB LIBR DIST ILL,Cook,IL,"Cook, IL",17031.0,17031.0,Libraries,40615.0,...,Other,AGC,3.897,4.897,625000,100.846,630287.50,107.025,668906.25,38618.75
3,733123BR3,HTM,POPLAR CREEK PUB LIBR DIST ILL,Cook,IL,"Cook, IL",17031.0,17031.0,Libraries,40615.0,...,Other,AGC,3.948,4.961,625000,100.989,631181.25,109.377,683606.25,52425.00
4,733123BS1,HTM,POPLAR CREEK PUB LIBR DIST ILL,Cook,IL,"Cook, IL",17031.0,17031.0,Libraries,40615.0,...,Other,AGC,4.031,5.066,625000,101.928,637050.00,112.644,704025.00,66975.00

In [25]:
#df_sample.isna().sum()
df_sample_small = df_sample[['FIPS_txt','White %']]
df_sample_small = df_sample_small.dropna()
df_sample_small.isna().sum()
df_sample_small.head()

   FIPS_txt   White %
0   17031.0  0.614625
1   17031.0  0.614625
2   17031.0  0.614625
3   17031.0  0.614625
4   17031.0  0.614625

In [27]:
colorscale = ["#f7fbff", "#ebf3fb", "#deebf7", "#d2e3f3", "#c6dbef", "#b3d2e9", "#9ecae1",
    "#85bcdb", "#6baed6", "#57a0ce", "#4292c6", "#3082be", "#2171b5", "#1361a9",
    "#08519c", "#0b4083", "#08306b"
]
endpts = list(np.linspace(1, 12, len(colorscale) - 1))
fips = df_sample_small['FIPS_txt'].tolist()
values = df_sample_small['White %'].tolist()

fig = ff.create_choropleth(
    fips = fips, values = values, scope = ['usa'],
    binning_endpoints = endpts, colorscale = colorscale,
    show_state_data = False,
    show_hover = True, centroid_marker = {
        'opacity': 0
    },
    asp = 2.9,
    title = 'SVB Race Stuff',
    legend_title = 'Race % White'
)
py.iplot(fig, filename = 'choropleth_full_race')

C:\Users\ryguy\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py:6692: FutureWarning:

Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.